name: tatc_env
channels:
  - conda-forge
dependencies:
  - python
  - cartopy=0.18.0
  - geopandas=0.9.0
  - geoplot=0.4.3
  - numba
  - numpy
  - pandas
  - pip
  - pydantic=1.8.2
  - pyproj=3.1.0
  - shapely=1.7.1
  - skyfield
  - sgp4
